# Test Endpoint (Add new Admin)
POST http://127.0.0.1:8000/add-new-admin
Content-Type: application/json

{
    "loginToken": "xkTIijaVqHSCAvZ-GDzZ9pRCr45_fJLQudu4uTgnbG4=",
    "fullName": "farland",
    "username": "farland",
    "password": "farland",
    "level": 3
}

###

# Test Auth Endpoint (OTP Generation)
POST http://127.0.0.1:8000/add-new
Content-Type: application/json

{
    "loginToken": "xkTIijaVqHSCAvZ-GDzZ9pRCr45_fJLQudu4uTgnbG4=",
    "fullName": "farland",
    "username": "farland",
    "password": "farland",
    "level": 3
}

###

### Add Online Order Test
POST https://zmt.basirsoft.tech/add-online-order
Content-Type: application/json

{
  "api": "123456",
  "firstName": "Ali",
  "lastName": "Ahmadi",
  "phone": "+93700111222",
  "email": "ali@example.com",
  "country": "Afghanistan",
  "address": "Kabul, District 10",
  "city": "Kabul",
  "state": "Kabul",
  "zipCode": "1001",
  "paymentMethod": "Cash",
  "cartItems": "[{\"id\": 1, \"name\": \"Curtain A\", \"qty\": 2}]",
  "totalAmount": 2000,
  "notes": "Deliver ASAP"
}

### Subscribe to Newsletter Test
GET https://zmt.basirsoft.tech/subscribe-newsletter?email=tester@example.com

### MAIL TEST
GET https://zmt.basirsoft.tech/send-html-mail?loginToken=xkTIijaVqHSCAvZ-GDzZ9pRCr45_fJLQudu4uTgnbG4%3D&email=ba3irzurmati@gmail.com&subject=Newsletter%20Confirmation&html_content=<h1>Test</h1>&text_content=Test%20Body
