from .login import router as login_router
from .dashboard import router as dashboard_router
from .user import router as user_router
from .product import router as product_router
from .bill import router as bill_router
from .roll import router as roll_router
from .purchase import router as purchase_router
from .supplier import router as supplier_router
from .entity import router as entity_router
from .sync import router as sync_router
from .search import router as search_router
from .report import router as report_router
from .expense import router as expense_router
from .payment import router as payment_router
from .miscellaneous import router as misc_router
from .earning import router as earning_router
from .pardaaf import router as pardaaf_router
from .print import router as print_router
from .telegram import router as telegram_router
